version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - smooks/core-committers
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  reviewers:
  - smooks/core-committers
